#!/usr/bin/env python3
"""Write paper/<run>/summary.md: the headline comparisons, computed from the run's tables.

Every number is read from paper/<run>/tables/*.csv; nothing is typed by hand.
Run after 06_evaluate.py (respects MAKD_CONFIG).
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from makd.common import load_config  # noqa: E402

LABEL = {"T_oracle": "Teacher, full data", "KD_state": "Distilled student (state)",
         "KD_pooled": "Distilled student (pooled)", "B3_state": "No distillation (state)",
         "B3_pooled": "No distillation (pooled)", "B1_teacher_meanimp": "Teacher + mean imputation",
         "B2_teacher_iterimp": "Teacher + iterative imputation",
         "B4_logistic_pooled": "Logistic + missing indicators"}
ORDER = list(LABEL)


def gap_table(M: pd.DataFrame) -> pd.DataFrame:
    T = M[M.model == "T_oracle"].set_index("state")
    rows = []
    for m in ORDER:
        g = M[M.model == m].set_index("state")
        if g.empty:
            continue
        d = g.ppv_alert - T.ppv_alert.reindex(g.index)
        rows.append({"Model": LABEL[m], "States": len(g), "AUROC (median)": f"{g.auroc.median():.3f}",
                     "PPV @10% (median)": f"{100 * g.ppv_alert.median():.1f}%",
                     "PPV gap, median (pts)": f"{100 * d.median():+.2f}",
                     "PPV gap, worst state (pts)": f"{100 * d.min():+.2f}",
                     "Sens gap, median (pts)": f"{100 * (g.sens_alert - T.sens_alert.reindex(g.index)).median():+.2f}",
                     "ICI (median, pts)": f"{100 * g.ici.median():.2f}"})
    return pd.DataFrame(rows)


def main():
    cfg = load_config()
    paper = cfg["paths"]["paper"]
    tabs = paper / "tables"
    M = pd.read_csv(tabs / "metrics_by_state.csv")
    M = M[M.calibration == "raw"]
    B = pd.read_csv(tabs / "bootstrap_selected_states.csv")
    N = pd.read_csv(tabs / "natural_missingness.csv")
    N = N[N.calibration == "raw"]
    y = cfg["years"]
    label = cfg.get("run_label", "main")
    pilot = label == "pilot"
    out = [f"# {label.capitalize()} results summary (generated by code/09_summary.py)", ""]
    if label == "available":
        out += [f"> AVAILABLE-DATA design: train {', '.join(map(str, y['train']))} (2023 split 80/20 with the tune set), "
                f"test {y['test'][0]}. Per-state students for 8 states; pooled students for all 51. Draft: verify before use.", ""]
    if pilot:
        out += ["> PILOT: train on 80% of 2023, tune on the other 20%, test on 2024; reduced samples; per-state "
                "students for 8 states. Feasibility evidence only; not for quotation (V12).", ""]
    for (o, mech), g in M.groupby(["outcome", "mechanism"], sort=False):
        out += [f"## {o}, {mech}", "", gap_table(g).to_markdown(index=False), ""]
        d = B[(B.outcome == o) & (B.mechanism == mech) & (B.model == "DIFF_KDstate_minus_B3state")]
        if len(d):
            out.append("Paired bootstrap, distilled minus non-distilled state student (95% CI):")
            for _, r in d.iterrows():
                out.append(f"- {r.state}: AUROC {r.auroc_lo:+.4f} to {r.auroc_hi:+.4f}; "
                           f"PPV@10% {100 * r.ppv_alert_lo:+.2f} to {100 * r.ppv_alert_hi:+.2f} pts")
            out.append("")
    out += ["## Natural missingness (real 2024 records with at least one masked item unknown)", ""]
    nn = N.pivot_table(index=["outcome", "model"], columns="trained_under", values=["auroc", "ppv_alert"])
    nn.columns = [f"{a} ({b})" for a, b in nn.columns]
    out += [nn.round(3).reset_index().to_markdown(index=False), ""]
    nb = tabs / "natural_missingness_bootstrap.csv"
    if nb.exists():
        Bn = pd.read_csv(nb)
        Bn = Bn[Bn.model.str.startswith("DIFF_")].copy()
        Bn["comparison"] = Bn.model.str.replace("DIFF_KDpooled_minus_", "distilled (pooled) minus ", regex=False)
        Bn["AUROC diff, 95% CI"] = Bn.apply(lambda r: f"{r.auroc_lo:+.4f} to {r.auroc_hi:+.4f}", axis=1)
        Bn["PPV@10% diff, 95% CI (pts)"] = Bn.apply(lambda r: f"{100 * r.ppv_alert_lo:+.2f} to {100 * r.ppv_alert_hi:+.2f}", axis=1)
        out += ["### Paired bootstrap on naturally incomplete records", "",
                Bn[["outcome", "trained_under", "comparison", "AUROC diff, 95% CI", "PPV@10% diff, 95% CI (pts)"]]
                .to_markdown(index=False), ""]
    (paper / "summary.md").write_text("\n".join(out) + "\n")
    print(f"[summary] -> {paper / 'summary.md'}")


if __name__ == "__main__":
    main()
